# Generated by Django 3.2.16 on 2023-10-28 14:05

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[recipes.validators.hex_validator], verbose_name='Цвет в HEX'),
        ),
    ]
