# Generated by Django 3.2.16 on 2023-11-05 21:27

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name', 'pub_date'), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Например: #FFF или #0F0F0F', max_length=7, validators=[recipes.validators.hex_validator], verbose_name='Цвет в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Не более 200 символов. Буквы, цифры и только @/./+/-/_', max_length=200, verbose_name='Уникальный слаг'),
        ),
    ]
